import { NPC, Location, Player, GameTime } from '@/types/game';

export const initialTime: GameTime = {
  tick: 0,
  hour: 18, // Start in the evening
  day: 1,
  week: 1,
  season: 'autumn',
  year: 1,
};

export const initialPlayer: Player = {
  name: 'Traveler',
  stats: {
    health: 100,
    energy: 80,
    mood: 60,
    wealth: 25,
    hunger: 70,
  },
  inventory: [
    {
      id: 'item_worn_dagger',
      name: 'Worn Dagger',
      description: 'A simple dagger with a worn handle. Better than nothing.',
      type: 'weapon',
      value: 5,
    },
    {
      id: 'item_bread',
      name: 'Stale Bread',
      description: 'A loaf of bread, a bit stale but still edible.',
      type: 'consumable',
      value: 2,
    },
  ],
  reputation: {},
  knownInformation: [],
  currentLocation: 'tavern_main',
};

export const initialNPCs: Record<string, NPC> = {
  npc_martha: {
    id: 'npc_martha',
    name: 'Martha',
    age: 34,
    occupation: 'Tavern Owner',
    homeLocation: 'tavern_main',
    description: 'A sturdy woman with sharp eyes and flour-dusted hands. She runs the Rusty Nail with an iron grip.',
    stats: { health: 100, energy: 75, mood: 60, wealth: 250 },
    traits: ['hardworking', 'suspicious', 'protective', 'gossip'],
    schedule: {
      6: { location: 'tavern_kitchen', activity: 'cooking breakfast' },
      8: { location: 'tavern_main', activity: 'serving customers' },
      12: { location: 'tavern_kitchen', activity: 'preparing lunch' },
      14: { location: 'market', activity: 'shopping for supplies' },
      16: { location: 'tavern_main', activity: 'serving the evening crowd' },
      22: { location: 'tavern_upstairs', activity: 'sleeping' },
    },
    memory: [],
    relationships: {
      player: { affection: 0, trust: 0, fear: 0, respect: 5 },
      npc_thomas: { affection: -30, trust: -50, fear: 0, respect: 0 },
      npc_guard_james: { affection: 40, trust: 60, fear: 0, respect: 30 },
    },
    desires: ['protect_daughter', 'expand_business', 'find_husband'],
    secrets: ['owes_money_to_merchants_guild', 'daughter_is_sick'],
    currentLocation: 'tavern_main',
    currentActivity: 'serving the evening crowd',
  },
  npc_thomas: {
    id: 'npc_thomas',
    name: 'Thomas the Rat',
    age: 28,
    occupation: 'Petty Thief',
    homeLocation: 'alley',
    description: 'A wiry man with nervous eyes that dart about constantly. His clothes are patched and worn.',
    stats: { health: 70, energy: 60, mood: 40, wealth: 15 },
    traits: ['cunning', 'greedy', 'fearful', 'secretive'],
    schedule: {
      6: { location: 'alley', activity: 'sleeping rough' },
      10: { location: 'market', activity: 'pickpocketing' },
      14: { location: 'tavern_main', activity: 'drinking and listening' },
      18: { location: 'alley', activity: 'planning next score' },
      22: { location: 'alley', activity: 'sleeping' },
    },
    memory: [],
    relationships: {
      player: { affection: 0, trust: -10, fear: 0, respect: 0 },
      npc_martha: { affection: -20, trust: -30, fear: 10, respect: 0 },
      npc_guard_james: { affection: -50, trust: -50, fear: 40, respect: 0 },
    },
    desires: ['get_rich_quick', 'avoid_guards', 'find_big_score'],
    secrets: ['knows_secret_entrance_to_manor', 'witnessed_murder_last_month'],
    currentLocation: 'tavern_main',
    currentActivity: 'drinking and listening',
  },
  npc_guard_james: {
    id: 'npc_guard_james',
    name: 'Guard Captain James',
    age: 42,
    occupation: 'Town Guard Captain',
    homeLocation: 'barracks',
    description: 'A tall, weathered man with a prominent scar across his left cheek. His armor is well-maintained.',
    stats: { health: 120, energy: 85, mood: 55, wealth: 80 },
    traits: ['brave', 'honest', 'protective', 'calm'],
    schedule: {
      5: { location: 'barracks', activity: 'waking and preparing' },
      6: { location: 'market', activity: 'morning patrol' },
      12: { location: 'tavern_main', activity: 'lunch break' },
      14: { location: 'town_square', activity: 'afternoon patrol' },
      20: { location: 'tavern_main', activity: 'off-duty drink' },
      23: { location: 'barracks', activity: 'sleeping' },
    },
    memory: [],
    relationships: {
      player: { affection: 0, trust: 5, fear: 0, respect: 5 },
      npc_martha: { affection: 30, trust: 40, fear: 0, respect: 20 },
      npc_thomas: { affection: -40, trust: -60, fear: 0, respect: -20 },
    },
    desires: ['maintain_order', 'catch_thomas', 'retire_peacefully'],
    secrets: ['takes_bribes_from_merchants', 'loved_woman_who_died'],
    currentLocation: 'tavern_main',
    currentActivity: 'off-duty drink',
  },
  npc_old_edgar: {
    id: 'npc_old_edgar',
    name: 'Old Edgar',
    age: 67,
    occupation: 'Retired Adventurer',
    homeLocation: 'tavern_main',
    description: 'A grizzled old man with milky eyes and gnarled hands. He sits in the corner, nursing his ale.',
    stats: { health: 50, energy: 30, mood: 45, wealth: 120 },
    traits: ['curious', 'friendly', 'secretive', 'calm'],
    schedule: {
      8: { location: 'tavern_main', activity: 'having breakfast' },
      10: { location: 'market', activity: 'wandering' },
      12: { location: 'tavern_main', activity: 'telling stories' },
      18: { location: 'tavern_main', activity: 'drinking and reminiscing' },
      22: { location: 'tavern_upstairs', activity: 'sleeping' },
    },
    memory: [],
    relationships: {
      player: { affection: 10, trust: 0, fear: 0, respect: 0 },
      npc_martha: { affection: 50, trust: 40, fear: 0, respect: 20 },
      npc_guard_james: { affection: 20, trust: 30, fear: 0, respect: 30 },
    },
    desires: ['share_knowledge', 'find_worthy_heir', 'die_peacefully'],
    secrets: ['knows_location_of_ancient_treasure', 'was_once_famous_hero'],
    currentLocation: 'tavern_main',
    currentActivity: 'drinking and reminiscing',
  },
};

export const initialLocations: Record<string, Location> = {
  tavern_main: {
    id: 'tavern_main',
    name: 'The Rusty Nail - Main Hall',
    description: 'The main hall of the tavern is warm and smoky. A large hearth crackles in the corner, casting dancing shadows across the rough wooden tables. The smell of ale and roasting meat fills the air.',
    connectedLocations: ['tavern_kitchen', 'tavern_upstairs', 'town_square'],
    npcsPresent: [],
    items: [],
    possibleEvents: ['bar_fight', 'stranger_arrives', 'drunk_confession'],
    timeDescriptions: {
      morning: 'Morning light streams through the dusty windows. A few early risers nurse their ales.',
      afternoon: 'The tavern is quiet, with only a handful of patrons taking refuge from the afternoon sun.',
      evening: 'The tavern bustles with activity. Workers crowd the bar, and laughter echoes off the walls.',
      night: 'The crowd has thinned. Only the hardiest drinkers remain, their conversations hushed.',
    },
  },
  tavern_kitchen: {
    id: 'tavern_kitchen',
    name: 'The Rusty Nail - Kitchen',
    description: 'A cramped kitchen with a large iron stove. Pots bubble and steam rises. Dried herbs hang from the ceiling.',
    connectedLocations: ['tavern_main'],
    npcsPresent: [],
    items: [
      { id: 'item_kitchen_knife', name: 'Kitchen Knife', description: 'A sharp knife for food preparation.', type: 'weapon', value: 3 },
    ],
    possibleEvents: ['cooking_accident', 'rat_sighting'],
  },
  tavern_upstairs: {
    id: 'tavern_upstairs',
    name: 'The Rusty Nail - Upstairs',
    description: 'A narrow hallway with several doors leading to small rooms. The floorboards creak with each step.',
    connectedLocations: ['tavern_main'],
    npcsPresent: [],
    items: [],
    possibleEvents: ['overheard_conversation', 'locked_door_mystery'],
  },
  town_square: {
    id: 'town_square',
    name: 'Town Square',
    description: 'The heart of the town. A weathered fountain stands in the center, and cobblestone paths lead in all directions.',
    connectedLocations: ['tavern_main', 'market', 'alley'],
    npcsPresent: [],
    items: [],
    possibleEvents: ['town_crier', 'public_execution', 'traveling_merchant'],
    timeDescriptions: {
      morning: 'The square is coming alive as merchants set up their stalls and townsfolk begin their day.',
      afternoon: 'The square bustles with activity. Children play near the fountain while adults go about their business.',
      evening: 'The crowds thin as people head home for supper. The fountain catches the golden evening light.',
      night: 'The square is nearly empty. A lone guard patrols, and the fountain gurgles softly.',
    },
  },
  market: {
    id: 'market',
    name: 'Market District',
    description: 'Rows of stalls and shops line the narrow streets. The air is filled with the calls of vendors and the smell of spices.',
    connectedLocations: ['town_square'],
    npcsPresent: [],
    items: [],
    possibleEvents: ['pickpocket_attempt', 'rare_item_for_sale', 'argument_between_merchants'],
  },
  alley: {
    id: 'alley',
    name: 'Dark Alley',
    description: 'A narrow, shadowy passage between buildings. Refuse piles against the walls, and rats scurry in the darkness.',
    connectedLocations: ['town_square'],
    npcsPresent: [],
    items: [],
    possibleEvents: ['mugging_attempt', 'secret_meeting', 'hidden_cache'],
  },
};
