project_id = "hrlvdxoopcxtjrelhncf"

[functions.generate-portrait]
verify_jwt = false

[functions.generate-npc-portrait]
verify_jwt = false

[functions.generate-npc-dialogue]
verify_jwt = false

[functions.generate-adventure]
verify_jwt = false

[functions.generate-scene-image]
verify_jwt = false
